research_task:
  description: >
    Conduct a thorough research about {company} Focus on:
    1. Current company status and health
    2. Historical Company Performance
    3. Major Challenges and Opportunties
    4. Recent news and events
    5. Future Outlook and potential developments

    Make sure to organize your findings in a structured format with clear sections
  expected_output: >
    A comprehensive research document with well-organized sections covering all the requested
    aspects of {company}. Include specific facts, figures, and examples where relevant

  agent: researcher
  output_file: output/research.md

analysis_task:
  description: >
    Analyze the research findings and create a comprehensive report on {company}.
    Your report should:
    1. Begin with an executive summary
    2. Include all key information from research
    3. Provide insightful analysis of trends and patterns
    4. Offer a market outlook for company, noting that this should not be used for trading decisions
    5. Be formatted in a professional, easy-to-read style with clear headings

  expected_output: >
    A polished, professional report on {company} that presents the resarch findings with 
    added analysis and insights. The report should be well-structured
    with an executive summary, main sections, and conclusions.
  agent: analyst
  context:
    - research_task
  output_file: output/report.md